language: ruby
rvm:
  - 2.4

branches:
  only:
    - master

cache: bundler

before_install:
  - nvm install node

install:
  - bundle install --path vendor/bundle
  - npm install

before_script:
  - git config --global user.name '${GIT_NAME}'
  - git config --global user.email '${GIT_NAME}'
  - git remote set-url origin https://iagodahlem:${GITHUB_TOKEN}@github.com/iagodahlem/insiter.io.git

script:
  - bundle exec middleman deploy
