version: "2"

services:
  web:
    build: .
    command: "bundle exec middleman serve"
    working_dir: /app
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    ports:
      - "4567:4567"

volumes:
  node_modules:
